development:
  adapter: postgresql
  encoding: unicode
  database: goehlert_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: goehlert_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: goehlert_production
  pool: 5
